// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © piecioshka

//@version=6
indicator('📈 1x MA = Moving Average (by PK)', shorttitle='1x MA', overlay = true)

aColor = color.white

aLen = input(20, 'Długość')
aType = input.string(title='Typ', options=['SMA', 'EMA', 'WMA', 'VWMA', 'RMA'], defval='SMA')

aSeries = switch aType
    'SMA' => ta.sma(close, aLen)
    'EMA' => ta.ema(close, aLen)
    'WMA' => ta.wma(close, aLen)
    'VWMA' => ta.vwma(close, aLen)
    'RMA' => ta.rma(close, aLen)
    => na

plot(aSeries, 'MA', color=color.new(aColor, 30), linewidth=2, force_overlay=true)
