// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Piotr Kowalski "piecioshka"

//@version=6
indicator('📈 3x MA = Moving Average (by PK)', shorttitle='3x MA', overlay = true)

aColor = color.rgb(237, 197, 57)
bColor = color.rgb(141, 68, 57)
cColor = color.rgb(194, 59, 47)

aLen = input(4, 'Długość', group='Krótki')
aType = input.string(title='Typ', options=['SMA', 'EMA', 'WMA', 'VWMA', 'RMA'], group='Krótki', defval='SMA')
aSeries = switch aType
    'SMA' => ta.sma(close, aLen)
    'EMA' => ta.ema(close, aLen)
    'WMA' => ta.wma(close, aLen)
    'VWMA' => ta.vwma(close, aLen)
    'RMA' => ta.rma(close, aLen)
    => na

bLen = input(9, 'Długość', group='Średni')
bType = input.string(title='Typ', options=['SMA', 'EMA', 'WMA', 'VWMA', 'RMA'], group='Średni', defval='SMA')
bSeries = switch bType
    'SMA' => ta.sma(close, bLen)
    'EMA' => ta.ema(close, bLen)
    'WMA' => ta.wma(close, bLen)
    'VWMA' => ta.vwma(close, bLen)
    'RMA' => ta.rma(close, bLen)
    => na

cLen = input(18, 'Długość', group='Długi')
cType = input.string(title='Typ', options=['SMA', 'EMA', 'WMA', 'VWMA', 'RMA'], group='Długi', defval='SMA')
cSeries = switch cType
    'SMA' => ta.sma(close, cLen)
    'EMA' => ta.ema(close, cLen)
    'WMA' => ta.wma(close, cLen)
    'VWMA' => ta.vwma(close, cLen)
    'RMA' => ta.rma(close, cLen)
    => na

plot(aSeries, 'Krótki', color=color.new(aColor, 0), linewidth=2, force_overlay=true)
plot(bSeries, 'Średni', color=color.new(bColor, 0), linewidth=2, force_overlay=true)
plot(cSeries, 'Długi', color=color.new(cColor, 0), linewidth=2, force_overlay=true)
