// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Piotr Kowalski "piecioshka"

// @version=6
indicator('Koperty', overlay = true)

// Dobre ustawienia dla kopert to:
// - 3% wokół prostej średniej 21-dniowej
// - 5% wokół prostej średniej 10-tygodniowy
// - 10% wokół prostej średniej 40-tygodniowej

aColor = color.rgb(56, 104, 174)
bColor = color.rgb(215, 107, 52)

len = input.int(title = 'Długość', defval = 21, minval = 1)
percent = input.float(title = 'Procent', defval = 3.0, minval = 0.1, step = 0.1)

aSeries = ta.sma(close, len)

center = plot(aSeries, 'SMA', color=color.new(color.white, 30), force_overlay=true)
plotUpper = plot(aSeries * (1 + percent / 100), color=aColor, force_overlay=true)
plotLower = plot(aSeries * (1 - percent / 100), color=bColor, force_overlay=true)

fill(plotUpper, center, color = color.new(aColor, 90))
fill(center, plotLower, color = color.new(bColor, 90))
