// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Piotr Kowalski "piecioshka"

// @version=6
indicator('Wstęgi Bollingera', shorttitle='Bollinger Bands', overlay = true)

aColor = color.rgb(114, 48, 131)
bColor = color.rgb(240, 199, 58)

len = input.int(20, 'SMA')

std = ta.stdev(close, len)
sma = ta.sma(close, len)
center = plot(sma, color=color.new(color.white, 30), force_overlay=true)
plotUpper = plot(sma + 2 * std, color=aColor, force_overlay=true)
plotLower = plot(sma - 2 * std, color=bColor, force_overlay=true)

fill(plotUpper, center, color = color.new(aColor, 90))
fill(center, plotLower, color = color.new(bColor, 90))
