// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Piotr Kowalski "piecioshka"

//@version=6
strategy('Strategy', overlay=true, fill_orders_on_standard_ohlc = true)

aLen = input(50, 'Short SMA period')
bLen = input(200, 'Long SMA period')

aSeries = ta.sma(close, aLen)
bSeries = ta.sma(close, bLen)

plot(aSeries, 'Short SMA', color=color.aqua, linewidth=2)
plot(bSeries, 'Long SMA', color=color.orange, linewidth=2)

if (ta.crossover(aSeries, bSeries))
    strategy.entry('My Long Entry Id', strategy.long)

if (ta.crossunder(aSeries, bSeries))
    strategy.entry('My Short Entry Id', strategy.short)
