// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © piecioshka

//@version=6
strategy('📈 Strategy (by PK)', overlay=true, fill_orders_on_standard_ohlc = true)

a = input(50, 'Krótki okres SMA')
b = input(200, 'Długi okres SMA')

aSeries = ta.sma(close, a)
bSeries = ta.sma(close, b)

longCondition = ta.crossover(aSeries, bSeries)
if (longCondition)
    strategy.entry('My Long Entry Id', strategy.long)

shortCondition = ta.crossunder(aSeries, bSeries)
if (shortCondition)
    strategy.entry('My Short Entry Id', strategy.short)
