// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © piecioshka

//@version=6
strategy("PK", overlay=true, fill_orders_on_standard_ohlc = true)

a = 50
b = 200

longCondition = ta.crossover(ta.sma(close, a), ta.sma(close, b))
if (longCondition)
    strategy.entry("My Long Entry Id", strategy.long)

shortCondition = ta.crossunder(ta.sma(close, a), ta.sma(close, b))
if (shortCondition)
    strategy.entry("My Short Entry Id", strategy.short)
