// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © piecioshka

//@version=6
indicator("😎 2x MA (by PK)", overlay = true)

aColor = color.rgb(56, 104, 174)
bColor = color.rgb(215, 107, 52)

aLen = input(50, 'Długość', group="Krótki")
aType = input.string(title='Typ', options=['SMA', 'EMA', 'WMA', 'VWMA', 'RMA'], group="Krótki", defval='SMA')
aSeries = switch aType
    'SMA' => ta.sma(close, aLen)
    'EMA' => ta.ema(close, aLen)
    'WMA' => ta.wma(close, aLen)
    'VWMA' => ta.vwma(close, aLen)
    'RMA' => ta.rma(close, aLen)
    => na

bLen = input(200, 'Długość', group="Długi")
bType = input.string(title='Typ', options=['SMA', 'EMA', 'WMA', 'VWMA', 'RMA'], group="Długi", defval='SMA')
bSeries = switch bType
    'SMA' => ta.sma(close, bLen)
    'EMA' => ta.ema(close, bLen)
    'WMA' => ta.wma(close, bLen)
    'VWMA' => ta.vwma(close, bLen)
    'RMA' => ta.rma(close, bLen)
    => na

plot(aSeries, 'Krótki', color=color.new(aColor, 30), linewidth=2, force_overlay=true)
plot(bSeries, 'Długi', color=color.new(bColor, 30), linewidth=2, force_overlay=true, linestyle=plot.linestyle_dotted)

if (ta.crossover(aSeries, bSeries))
    line.new(bar_index, high, bar_index, low, color=color.new(color.green, 70), width=1, style=line.style_dashed, extend=extend.both)
    label.new(bar_index, aSeries, "BUY OPEN", color=color.new(color.green, 50), style=label.style_label_up, size=size.normal, force_overlay=true)
    alert("Sygnał OTWARCIA pozycji DŁUGIEJ (LONG)!", alert.freq_once_per_bar_close)

if (ta.crossunder(aSeries, bSeries))
    line.new(bar_index, high, bar_index, low, color=color.new(color.red, 70), width=1, style=line.style_dashed, extend=extend.both)
    label.new(bar_index, aSeries, "BUY CLOSE", color=color.new(color.red, 50), style=label.style_label_down, size=size.normal, force_overlay=true)
    alert("Sygnał ZAMKNIĘCIA pozycji DŁUGIEJ (LONG)!", alert.freq_once_per_bar_close)
