// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © piecioshka

//@version=6
indicator("😎 2x SMA (by PK)", overlay = true)

colorA = color.green
colorB = color.red

a = input(50, 'Krótki okres SMA')
b = input(200, 'Długi okres SMA')

aSMA = ta.sma(close, a)
bSMA = ta.sma(close, b)

plot(aSMA, 'Krótki', color=color.new(colorA, 30), linewidth=2, force_overlay=true)
plot(bSMA, 'Długi', color=color.new(colorB, 30), linewidth=2, force_overlay=true)

if (ta.crossover(aSMA, bSMA))
    label.new(bar_index, high, "BUY OPEN", color=color.new(colorA, 50), style=label.style_label_down, size=size.normal, force_overlay=true)

if (ta.crossunder(aSMA, bSMA))
    label.new(bar_index, low, "BUY CLOSE", color=color.new(colorB, 50), style=label.style_label_up, size=size.normal, force_overlay=true)
