// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © piecioshka

//@version=6
indicator("😎 3x MA (by PK)", overlay = true)

a = input(4, 'Krótki okres SMA')
b = input(9, 'Średni okres SMA')
c = input(18, 'Długi okres SMA')

aSMA = ta.sma(close, a)
bSMA = ta.sma(close, b)
cSMA = ta.sma(close, c)

plot(aSMA, 'Krótki', color=color.new(#ffcb1f, 0), linewidth=2, force_overlay=true)
plot(bSMA, 'Średni', color=color.new(#d55c00, 0), linewidth=2, force_overlay=true)
plot(cSMA, 'Długi', color=color.new(#7e2600, 0), linewidth=2, force_overlay=true)

if (ta.crossover(aSMA, bSMA))
    label.new(bar_index, high, "", color=color.new(color.green, 50), style=label.style_label_down, size=size.large, force_overlay=true)

if (ta.crossunder(aSMA, bSMA))
    label.new(bar_index, low, "", color=color.new(color.red, 50), style=label.style_label_up, size=size.large, force_overlay=true)
