// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © piecioshka

//@version=6
indicator("😎 3x SMA (by PK)", overlay = true)

colorA = color.rgb(237, 197, 57)
colorB = color.rgb(141, 68, 57)
colorC = color.rgb(194, 59, 47)

a = input(4, 'Krótki okres SMA')
b = input(9, 'Średni okres SMA')
c = input(18, 'Długi okres SMA')

aSMA = ta.sma(close, a)
bSMA = ta.sma(close, b)
cSMA = ta.sma(close, c)

plot(aSMA, 'Krótki', color=color.new(colorA, 0), linewidth=2, force_overlay=true)
plot(bSMA, 'Średni', color=color.new(colorB, 0), linewidth=2, force_overlay=true)
plot(cSMA, 'Długi', color=color.new(colorC, 0), linewidth=2, force_overlay=true)
