// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © piecioshka

//@version=6
indicator("😎 MACD (by PK)")

macdColor = color.rgb(56, 104, 174)
signalColor = color.rgb(215, 107, 52)

aLen = input(12, 'Szybsza (krótsza)', group="Szybsza (krótsza)")
aType = input.string(title='Typ', options=['SMA', 'EMA', 'WMA', 'VWMA', 'RMA'], group="Szybsza (krótsza)", defval='EMA')
aSeries = switch aType
    'SMA' => ta.sma(close, aLen)
    'EMA' => ta.ema(close, aLen)
    'WMA' => ta.wma(close, aLen)
    'VWMA' => ta.vwma(close, aLen)
    'RMA' => ta.rma(close, aLen)
    => na

bLen = input(26, 'Szybsza (dłuższa)', group="Szybsza (dłuższa)")
bType = input.string(title='Typ', options=['SMA', 'EMA', 'WMA', 'VWMA', 'RMA'], group="Szybsza (dłuższa)", defval='EMA')
bSeries = switch bType
    'SMA' => ta.sma(close, bLen)
    'EMA' => ta.ema(close, bLen)
    'WMA' => ta.wma(close, bLen)
    'VWMA' => ta.vwma(close, bLen)
    'RMA' => ta.rma(close, bLen)
    => na

macd = aSeries - bSeries

cLen = input(9, 'Wolniejsza', group="Wolniejsza")
cType = input.string(title='Typ', options=['SMA', 'EMA', 'WMA', 'VWMA', 'RMA'], group="Wolniejsza", defval='EMA')
cSeries = switch cType
    'SMA' => ta.sma(macd, cLen)
    'EMA' => ta.ema(macd, cLen)
    'WMA' => ta.wma(macd, cLen)
    'VWMA' => ta.vwma(macd, cLen)
    'RMA' => ta.rma(macd, cLen)
    => na

plot(macd, 'MACD', color=macdColor, linewidth=2)
plot(cSeries, 'Signal', color=signalColor, linewidth=2, linestyle=plot.linestyle_dotted)

histogram = macd - cSeries

histColor = histogram >= 0 ? color.new(color.green, 50) : color.new(color.red, 50)
plot(histogram, 'Histogram', color=histColor, linewidth=2, style=plot.style_columns)

hline(0, 'Zero', color=color.gray, linestyle=hline.style_solid)

if (ta.crossover(macd, cSeries))
    label.new(bar_index, macd, "BUY OPEN", color=color.new(color.green, 50), style=label.style_label_down, size=size.normal)
    alert("Sygnał OTWARCIA pozycji DŁUGIEJ (LONG)!", alert.freq_once_per_bar_close)

if (ta.crossunder(macd, cSeries))
    label.new(bar_index, macd, "BUY CLOSE", color=color.new(color.red, 50), style=label.style_label_up, size=size.normal)
    alert("Sygnał ZAMKNIĘCIA pozycji DŁUGIEJ (LONG)!", alert.freq_once_per_bar_close)
