// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © piecioshka

//@version=6
indicator("😎 Oscylator Stochastyczny (by PK)")

aLen = input(14, '%K Długość')
smothing = input(3, '%K Wygładzanie długości')
smaLen = input(3, '%D Długość SMA')

K = ta.sma(ta.stoch(close, high, low, aLen), smothing)
D = ta.sma(K, smaLen)


plot(K, 'Oscylator', color=color.blue, linewidth=2)
plot(D, 'Sygnał', color=color.orange, linewidth=2, linestyle=plot.linestyle_dotted)

top = hline(80, '', color=color.gray, linestyle=hline.style_dashed)
bottom = hline(20, '', color=color.gray, linestyle=hline.style_dashed)
fill(top, bottom, color = color.new(color.rgb(56, 104, 174), 90))

if (ta.crossunder(K, D) and K < 30)
    line.new(bar_index, high, bar_index, low, color=color.new(color.green, 70), width=1, style=line.style_dashed, extend=extend.both)
    line.new(bar_index, high, bar_index, low, color=color.new(color.green, 70), width=1, style=line.style_dashed, extend=extend.both, force_overlay=true)
    label.new(bar_index, K - 10, "BUY OPEN", color=color.new(color.green, 50), style=label.style_label_up, size=size.normal)
    alert("Sygnał OTWARCIA pozycji DŁUGIEJ (LONG)!", alert.freq_once_per_bar_close)

if (ta.crossover(K, D) and K > 70)
    line.new(bar_index, high, bar_index, low, color=color.new(color.red, 70), width=1, style=line.style_dashed, extend=extend.both)
    line.new(bar_index, high, bar_index, low, color=color.new(color.red, 70), width=1, style=line.style_dashed, extend=extend.both, force_overlay=true)
    label.new(bar_index, K + 10, "BUY CLOSE", color=color.new(color.red, 50), style=label.style_label_down, size=size.normal)
    alert("Sygnał ZAMKNIĘCIA pozycji DŁUGIEJ (LONG)!", alert.freq_once_per_bar_close)
